### ISSUE TITLE
Voting for guests

### ISSUE THREAD

**Issue by lex111** [TheRealJAG/Laravel-QuestionAnswer#2]
It's strange that the vote count increases / decreases when you click on the corresponding buttons, although after that a modal window appears with the message that you can only vote registered, and of course, after the page has been reloaded, the vote counter is the same as it was.

I think it's better to hide the voting buttons at all unregistered.

**Comment by TheRealJAG** [comment]
I've tried to fix the vote number on guest voting but I couldn't. I'll try and circle back and see what I can do. 

I'd rather keep them and promote user signups / logins.

**Comment by TheRealJAG** [comment]
@lex111 I was able to fix the issue you've mentioned and you can see it in action on the demo page. I'm going to close this issue. Thanks!
