### ISSUE TITLE
SQL issues

### ISSUE THREAD

**Issue by moumen-soliman** [TheRealJAG/Laravel-QuestionAnswer#20]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'qadb.votes' doesn't exist (SQL: select `questions`.*, sum(votes.vote) as vote_ttl from `questions` inner join `votes` on `questions`.`id` = `votes`.`question_id` where `questions`.`created_at` >= 2013-04-29 02:10:22 group by `questions`.`id` order by `vote_ttl` desc, `questions`.`created_at` desc limit 3)

**Comment by TheRealJAG** [comment]
Did you run migration?

**Comment by moumen-soliman** [comment]
when migrate , this error from terminal 

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL
  : alter table `questions` add constraint `questions_user_id_foreign` foreig
  n key (`user_id`) references `users` (`id`))



  [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

**Comment by moumen-soliman** [comment]
@TheRealJAG

**Comment by TheRealJAG** [comment]
I will check tonight when I get home.

**Comment by moumen-soliman** [comment]
ok i found solution say that : 

```
        Schema::table('questions', function($table) {
            $table->foreign('user_id')->references('id')->on('users');
        });
```

in every table , do that , separate part , i would that help

**Comment by TheRealJAG** [comment]
Can you create a pull request so I can merge?

**Comment by moumen-soliman** [comment]
this not work too , but i found this in forgein key issues from research about error

**Comment by Korzar** [comment]
There's a problem with the migration files in the repository. 
On "2017_04_09_000000_create_qna_schema.php" there is no creation statements for the "users" table, which is necessary for the rest of the migrations as there are references to said table.

In addition to that, you have to mark the foreign keys on the other tables as unsigned, so there isn't a type mismatch between the primary key of the original table and the foreign ones of the rest.

I attached a modified working copy of the file so people can try the application. I don't create a pull request as the right thing to do should be to create the migration files again from the Artisan console and update the repository. I will leave that to @TheRealJAG 

I also don't know if there are more tables missing that can affect the application other than "users", as the migrations are incomplete. @TheRealJAG could also bring some light about this issue. The ones I've got now are:

- answers

- migrations (created automatically by Laravel after running the migration files)

- notifications

- questions

- tags

- tags_questions

- users

- votes


Thanks!

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateQnaSchema extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
		
	Schema::create('users', function (Blueprint $table)
        {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });

        Schema::create('questions', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->string('question');
            $table->string('level')->default('Beginner');
            $table->boolean('solved')->default(false);
            $table->timestamps();
	    $table->foreign('user_id')->references('id')->on('users');
        });
		
        Schema::create('answers', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->integer('question_id')->unsigned();
            $table->text('answer');
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('question_id')->references('id')->on('questions');
        });

        Schema::create('votes', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('user_id')->unsigned();
            $table->integer('question_id')->nullable()->unsigned();
            $table->integer('answer_id')->nullable()->unsigned();
            $table->integer('vote');
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('question_id')->references('id')->on('questions');
            $table->foreign('answer_id')->references('id')->on('answers');
        });

        Schema::create('tags', function(Blueprint $table)
        {
            $table->increments('id');
            $table->string('name');
            $table->string('display');
            $table->timestamps();
            $table->softDeletes();
        });


        Schema::create('tags_questions', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('tag_id')->unsigned();
            $table->integer('question_id')->unsigned();
            $table->timestamps();
            $table->foreign('tag_id')->references('id')->on('tags');
            $table->foreign('question_id')->references('id')->on('questions');
            $table->unique(['tag_id', 'question_id']);
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tags_questions');
        Schema::dropIfExists('tags');
        Schema::dropIfExists('votes');
        Schema::dropIfExists('answers');
        Schema::dropIfExists('questions');
	Schema::dropIfExists('users');
    }
}
```

**Comment by joshxduncan** [comment]
Hey @TheRealJAG I'm encountering the same issue and wondering if you can confirm @Korzar 's solution. Are there any migrations missing?

Thanks a lot about to start on a project using this and just want to be sure!

**Comment by TheRealJAG** [comment]
@svaults I push a commit from @Korzar comments. Run your migrations and let me know if you still run into troubles and I'll close the issue. Thanks @Korzar! When I started I didn't build the migrations right from the start, causing all this pain. I appreciate it. 

https://github.com/TheRealJAG/Laravel-QuestionAnswer/commit/46a76bcbcd278e5e81765f71c4e1af4ca60d4e32
