### ISSUE TITLE
New question form not submitting

### ISSUE THREAD

**Issue by joshxduncan** [TheRealJAG/Laravel-QuestionAnswer#21]
@TheRealJAG Hello! I'm getting a bug where the new question form isn't submitting, on the demo site you link to as well as my local one. I'm seeing a js console type error that may be linked to it. Will poke around some more

Update: Looks like it's the twitter tags input js, it takes over the input field but doesn't have a "name" attr so that may be preventing it from submitting - when I remove that field, the request goes through

**Comment by TheRealJAG** [comment]
@svaults can you make a pull request and I'll take a look at it? Or post the changes here?

**Comment by joshxduncan** [comment]
@TheRealJAG I actually just removed the view code generating the "tags" input - my use case was a little different so I didn't need the tags field. I've never used that bootstrap tags lib before but the issue is it overrides the input field with its own input, but doesn't include the name tag on the new input, making it an invalid form field = no submit.

**Comment by itepifanio** [comment]
@TheRealJAG the problem only happens when there isn't a tag registered. When you insert a tag in the system the form works. I will pull a UX improvement.

**Comment by TheRealJAG** [comment]
This has been fixed in https://github.com/TheRealJAG/Laravel-QuestionAnswer/pull/22
