### ISSUE TITLE
Votes Migration

### ISSUE THREAD

**Issue by bryanrscott** [TheRealJAG/Laravel-QuestionAnswer#3]
Just wondering if there should be a migration for the votes model?

**Comment by bryanrscott** [comment]
Also I see in app\Tags.php  a reference to tags_questions table in the function tags() but can't locate the migration.   Just wondering maybe I am off base, and just missing something?

**Comment by TheRealJAG** [comment]
I need to make sure the migrations are current. I'll try and update today. You are right there might not be migrations for that.

**Comment by TheRealJAG** [comment]
I wasn't able to create the migration files, I had to create all the foreign keys and and the migrate tool wasn't playing friendly. I've updated the project with sql.txt that outlines all the tables. Make sure you're using the latest SQL to include the foreign keys. 

Are you able to create migration files for the tables after the raw SQL execution? When I tried the migration tool package I error out so I had to remove.

**Comment by bryanrscott** [comment]
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Models\Ref\Port;

class CreateFaqSchema extends Migration
{
    const SCHEMA = "" ;
    const TAG_TABLE = "tagging_tags" ;

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $tagTable = static::TAG_TABLE ;
        $schema =  static::SCHEMA ;

        if (!empty($schema)) {
            if (Schema::getConnection()->getDriverName() == 'pgsql') {
                DB::unprepared('CREATE SCHEMA IF NOT EXISTS "' . $schema . '"');
            }
        }
        if (!empty($schema)) {
            $schema = $schema . "." ;
        }

        Schema::create($schema . 'questions', function(Blueprint $table)
        {
            $table->increments('id');
            $table->integer('user_id');
            $table->string('question');
            $table->string('level')->default('Beginner');
            $table->boolean('solved')->default(false);
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users');
        });

        Schema::create($schema . 'answers', function(Blueprint $table) use ($schema)
        {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('question_id');
            $table->text('answer');
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('question_id')->references('id')->on($schema . 'questions');
        });

        Schema::create($schema . 'votes', function(Blueprint $table) use ($schema)
        {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('question_id');
            $table->integer('answer_id');
            $table->integer('vote');
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('question_id')->references('id')->on($schema . 'questions');
            $table->foreign('answer_id')->references('id')->on($schema . 'answers');
        });

        Schema::create($schema . 'tags', function(Blueprint $table)
        {
            $table->increments('id');
            $table->string('name');
            $table->string('display');
            $table->timestamps();
        });


        Schema::create($schema . 'tags_questions', function(Blueprint $table) use ($schema, $tagTable)
        {
            $table->increments('id');
            $table->integer('tag_id');
            $table->integer('question_id');
            $table->timestamps();
            $table->foreign('tag_id')->references('id')->on($schema . 'tags');
            $table->foreign('question_id')->references('id')->on($schema . 'questions');
            $table->unique(['tag_id', 'question_id']);
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        $schema = static::SCHEMA ;
        if (!empty($schema)) {
            $schema = $schema . "." ;
        }
        Schema::dropIfExists($schema . 'tags_questions');
        Schema::dropIfExists($schema . 'votes');
        Schema::dropIfExists($schema . 'answers');
        Schema::dropIfExists($schema . 'questions');

        # don't drop cascade as if everything is done right it should be not needed.
        # if not, it highlights the area that needs attention
        $schema = static::SCHEMA ;
        if (!empty($schema)) {
            if (Schema::getConnection()->getDriverName() == 'pgsql') {
                DB::unprepared('DROP SCHEMA IF EXISTS "' . $schema . '"');
            }
        }
    }
}
