### ISSUE TITLE
Create migration from current db schema

### ISSUE THREAD

**Issue by TheRealJAG** [TheRealJAG/Laravel-QuestionAnswer#5]
Need to create a migration routine from the sql.txt file in the project.

**Comment by bryanrscott** [comment]
Can this help?
https://github.com/bryanrscott/laravel-5-boilerplate-faq/blob/master/database/migrations/2017_04_09_000000_create_faq_schema.php

**Comment by TheRealJAG** [comment]
@bryanrscott yes. trying to think of the best way I can add that file to the project and give you credit for the contribution.

**Comment by bryanrscott** [comment]
Just happy to help

**Comment by TheRealJAG** [comment]
@bryanrscott Are you able to perform a pull request this file? https://github.com/TheRealJAG/Laravel-QnA/blob/master/database/migrations/2017_04_09_000000_create_schema.php

**Comment by bryanrscott** [comment]
Yep.  Will do tomorrow.  Getting late here

**Comment by TheRealJAG** [comment]
@bryanrscott good job! Merged with master branch. Thanks again!
