### ISSUE TITLE
Force lowercase on level

### ISSUE THREAD

**Issue by TheRealJAG** [TheRealJAG/Laravel-QuestionAnswer#9]

**Comment by bryanrscott** [comment]
In the Question model you could add something like

    /**
     * Always lowercase the level when we save it to the database
     */
    public function setLevelAttribute($value) {
        $this->attributes['level'] = strtolower($value);
    }

**Comment by TheRealJAG** [comment]
Thanks! I decided to keep the case when inserting but forced strtolower() in the question container.
